name: ESLint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  schedule:
    - cron: '38 4 * * 5'

jobs:
  build:
    name: Build TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  eslint:
    name: Run ESLint scanning
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run ESLint Fix
        run: npm run lint:fix

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npm run lint -- --format @microsoft/eslint-formatter-sarif --output-file reports/eslint-results.sarif
        continue-on-error: true

      - name: Check if SARIF file exists
        run: |
          if [ ! -f reports/eslint-results.sarif ]; then
            echo "ESLint SARIF file not found! Skipping upload."
            exit 1
          fi

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/eslint-results.sarif
          wait-for-processing: true